[package]
name = "cli-app"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.2.10"
sodiumoxide = "0.2.4"
base64 = "0.10.1"